<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQr40K1Z\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQr40K1Z/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQr40K1Z.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQr40K1Z\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerQr40K1Z\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Qr40K1Z',
    'container.build_id' => '8ee4fe04',
    'container.build_time' => 1542639528,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerQr40K1Z');
